"""sync models with existing tables

Revision ID: bf62574a1ed6
Revises: add_admission_number
Create Date: 2026-04-12 17:44:15.388392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf62574a1ed6'
down_revision = 'add_admission_number'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_place')
    with op.batch_alter_table('exam_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_result_created_at'))
        batch_op.drop_index(batch_op.f('ix_exam_result_student_id'))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('transaction_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'cash'"))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'2024'"))
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Term 1'"))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_student_admission_number'))
        batch_op.create_unique_constraint('uq_student_admission_number', ['admission_number'])
        batch_op.drop_column('class_teacher_id')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('class_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('qualification',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_teacher_class_name'))
        batch_op.drop_index(batch_op.f('idx_teacher_email'))
        batch_op.create_unique_constraint('uq_teacher_email', ['email'])
        batch_op.drop_column('credentials_file')
        batch_op.drop_column('name')
        batch_op.drop_column('joining_date')

    with op.batch_alter_table('teacher_login', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_teacher_login_username', ['username'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joining_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('credentials_file', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_teacher_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_teacher_class_name'), ['class_name'], unique=False)
        batch_op.alter_column('qualification',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('class_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('active')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_teacher_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_student_admission_number'), ['admission_number'], unique=1)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Term 1'"))
        batch_op.alter_column('year',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False,
               existing_server_default=sa.text("'2024'"))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'cash'"))
        batch_op.alter_column('transaction_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('exam_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_result_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_result_created_at'), ['created_at'], unique=False)

    op.create_table('exam_place',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('exam_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('exam_date', sa.DATETIME(), nullable=False),
    sa.Column('room_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('seat_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'exam_type', name=op.f('uq_student_exam_type'))
    )
    # ### end Alembic commands ###
