"""add admin_set_timestamp

Revision ID: d2a1ba3dd6f7
Revises: 32229fc16b61
Create Date: 2026-05-05 20:43:44.061989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a1ba3dd6f7'
down_revision = '32229fc16b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_payment')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('transaction_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'cash'"))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'2024'"))
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Term 1'"))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('next_of_kin_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('next_of_kin_relationship',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('next_of_kin_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_student_admission_number'))
        batch_op.create_unique_constraint(None, ['admission_number'])
        batch_op.drop_column('class_teacher_id')
        batch_op.drop_column('next_of_kin')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('teacher_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_set_timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('admin_set_timestamp')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_of_kin', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('class_teacher_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_student_admission_number'), ['admission_number'], unique=1)
        batch_op.alter_column('next_of_kin_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('next_of_kin_relationship',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('next_of_kin_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Term 1'"))
        batch_op.alter_column('year',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False,
               existing_server_default=sa.text("'2024'"))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'cash'"))
        batch_op.alter_column('transaction_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.create_table('_alembic_tmp_payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), server_default=sa.text("'cash'"), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'completed'"), nullable=False),
    sa.Column('payment_category', sa.VARCHAR(length=50), server_default=sa.text("'regular'"), nullable=False),
    sa.Column('year', sa.VARCHAR(length=10), server_default=sa.text("'2024'"), nullable=False),
    sa.Column('session', sa.VARCHAR(length=50), server_default=sa.text("'Term 1'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('last_modified', sa.DATETIME(), nullable=True),
    sa.Column('total_fee', sa.FLOAT(), server_default=sa.text('(1500.0)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
